# Generated by Django 4.0.6 on 2022-07-19 13:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsutationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=50)),
                ('clinic_logo', models.CharField(max_length=25)),
                ('physician_name', models.CharField(max_length=50)),
                ('physician_contact', models.CharField(max_length=10)),
                ('pt_first_name', models.CharField(max_length=25)),
                ('pt_last_name', models.CharField(max_length=25)),
                ('pt_dob', models.DateField()),
                ('pt_contact', models.CharField(max_length=10)),
                ('chief_complaint', ckeditor.fields.RichTextField(max_length=5000)),
                ('consultation_note', ckeditor.fields.RichTextField(max_length=5000)),
            ],
        ),
    ]
