# Generated by Django 4.0.6 on 2022-07-21 06:02

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consutationlist',
            name='pt_contact',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
