# Generated by Django 4.0.6 on 2022-07-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_consutationlist_pt_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsutationList',
            new_name='ConsultationList',
        ),
    ]
