# Generated by Django 4.0.6 on 2022-07-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_consutationlist_consultationlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationlist',
            name='physician_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultationlist',
            name='pt_contact',
            field=models.CharField(max_length=100),
        ),
    ]
